###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.6"
services:
  webserver:
    image: nginx:alpine
    container_name: api_ts3-nginx
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6666:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: api_ts3-php
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"
    ports:
      - "555:22"
